### ISSUE TITLE
Improve debugger labeling for string actions

### ISSUE THREAD

**Issue by ltk** [vigetlabs/microcosm#126]
![example](https://s3.amazonaws.com/vigesharing-is-vigecaring/lkurtz/mcsm-string-action-labels-debugger.gif)

Perhaps use the string

**Comment by nhunzaker** [comment]
Hmm. The label here _should_ be the function name, or fallback to `microcosm_action`. Is it possible to generate a test case for this?

https://github.com/vigetlabs/microcosm/blob/master/src/action/tag.js#L34

**Comment by ltk** [comment]
Yeah, I'll probably jam on this a bit tomorrow.

**Comment by ltk** [comment]
Looks like the `done` label is set correctly, however microcosm-debugger shows `fn.name`. We could always show `fn.done`, however for normal actions like `const updateCount = delta => delta` would show up as `updateCount_1` because of the stepper suffix. Maybe it's better anyway to display the actual tag even if it's a little uglier?

**Comment by nhunzaker** [comment]
Ah interesting. Let's show the ugly tag until we can cover all cases. This is a developer tool. Let's go with consistency.

**Comment by ltk** [comment]
:+1:

**Comment by ltk** [comment]
Well look at that, it's not ugly after all: https://github.com/vigetlabs/microcosm-debugger/blob/master/lib/components/list/list-item.jsx#L6

**Comment by nhunzaker** [comment]
Merely human :)

**Comment by ltk** [comment]
I think I fixed this in microcosm-debugger but forgot to push it up. will do that today.
