### ISSUE TITLE
What if we called Microcosm instances `repo`  instead of `app`?

### ISSUE THREAD

**Issue by nhunzaker** [vigetlabs/microcosm#128]
`var app = new Microcosm()` has been gnawing at me for a while. Particularly inside of Presenter `intent` callbacks, I really like how this reads:

```javascript
class PlanetsPresenter extends Presenter {

  onCreate(repo, props) {
    return repo.push(createPlanet, props)
  }

  // ...
  render() {
    return 
  }

}
```

Also open to other suggestions. `store` came to mind, but that's not really accurate.

**Comment by ltk** [comment]
victory
