### ISSUE TITLE
Releasing 10.0.0

### ISSUE THREAD

**Issue by nhunzaker** [vigetlabs/microcosm#151]
Let's keep the latest RC open for a few more days. In the meantime, this is the checklist I see:

- [x] Changelog
- [x] Upgrading guide
- [x] Update quick start (https://github.com/vigetlabs/microcosm-quickstart)
- [x] Update debugger (https://github.com/vigetlabs/microcosm-debugger)

**Comment by nhunzaker** [comment]
Getting there... last step will be to review all of the changes with the team. Additionally, we need to figure out if #155 imposes breaking changes. Ideally, we'd ship it with a minor release.

**Comment by nhunzaker** [comment]
Got it. Huzzah 10.0.0!

**Comment by djmccormick** [comment]
Congrats guys! What a great piece of software.

**Comment by nhunzaker** [comment]
@djmccormick aww, thanks :). Feel free to reach out with any questions!
