### ISSUE TITLE
Errors when domains don't have some methods

### ISSUE THREAD

**Issue by djmccormick** [vigetlabs/microcosm#152]
If a domain doesn't implement these functions, Microcosm (`10.0.0-rc3`) throws errors:

* `setup`
* `stage`
* `shouldCommit`

`bundle.js:95234 Uncaught TypeError: domain.setup is not a function` coming out of `addDomain`.

**Comment by djmccormick** [comment]
I fixed it like so:

	import Immutable from 'immutable';
	import Domain from 'microcosm/domain';

	export default class BaseDomain extends Domain {
		getInitialState() {
			return Immutable.Map();
		}

		commit(state) {
			return state.toJS();
		}
	}

**Comment by nhunzaker** [comment]
Huh. We implement safe defaults for those methods:

https://github.com/vigetlabs/microcosm/blob/master/src/domain.js

I wonder if Babel's loose mode class transpiler is doing something goofy. Before I go and blame other projects, I'll make sure we aren't doing anything silly, then I'll see if the output from the transpiler is problematic.
