### ISSUE TITLE
Rethinking server-side rendering. TLDR: serializing action history

### ISSUE THREAD

**Issue by nhunzaker** [vigetlabs/microcosm#162]
Our 9.x server-side rendering story is pretty nice (and can still be used with 10.x, just with some caveats):
1. Figure out what data needs to be fetched via static methods on route handlers
2. Serialize Microcosm via `repo.toJSON()`
3. Send the bundle + markup down to the user
4. Deserialize and hydrate Microcosm via `repo.patch(SEED_DATA, true)`
5. Render your app with the hydrated repo
### The problem

Presenters make this problematic because they fork their repo. If they call `addDomain` within `setup`, when the root microcosm serializes, it won't have that forked state.

So that's problematic, but _we have a powerful history API of every action that has occurred, and the state that it is in_.
### The solution

What if we recorded every action that happened and waited for history to resolve itself, this would look something like:
1. Figure out what data needs to be fetched via static methods on route handlers
2. Start "recording" actions, wait for all actions to resolve
3. Serialize action history
4. Send history + markup to the user
5. Roll forward Microcosm with the provided history data.
6. Render your app with the hydrated repo
### Advantages
1. Foremost, we can do server-side rendering with forks that add their own domains
2. Error management is simpler, we could just traverse action history to see if anything failed.
3. This might open up an opportunity for running Microcosm in a web/service worker, sending over new history "patches" as actions change.
### Disadvantages

Still figuring this one out. It _might_ be more complex. We'd also have to document that this would require action payloads to be serializable (but they've always been this way in my experience).
### Implementation

We'd want to implement a `toJSON` method on actions, that might be worth doing anyway. We'd also need to implement a way to pass a serialized history array into a Microcosm, but that might be as simple as:

``` javascript
if (Array.isArray(history)) {
    this.history = new History()
    history.forEach(action => this.history.append(action)
}
```

**Comment by nhunzaker** [comment]
Closing. This is invalid until we can figure out how to serialize functions over the wire. It might be more productive to instead send state for the Microcosm network.

**Comment by djmccormick** [comment]
@nhunzaker is it currently possible to get the state of a whole Microcosm network?
