### ISSUE TITLE
Sub-domains

### ISSUE THREAD

**Issue by nhunzaker** [vigetlabs/microcosm#184]
I think it's time that we have an actual class to describe Domains. We could use this to manage Sub-domains, which could operate relative to the key a Domain is mounted to:

```javascript
class Network extends Domain {

    setup (repo) {
        this.addDomain('nodes', Nodes) // mounted to ['network', 'nodes']
        this.addDomain('edges', Edges) // mounted to ['network','edges']
    }    

}

repo.addDomain('network', Network)
```

### Outstanding questions:

1. Do parent domains handle actions first, or after all subdomains have completed?

**Comment by nhunzaker** [comment]
I think I've got this wrong. Let's keep domains simple. Right now they don't implement any introspective methods. 

Instead, let's make it so that a Microcosm can mount other Microcosms at a given key path.

**Comment by greypants** [comment]
iiiiiiiiiiiiiiiiiiiiiiiiiiiinteresting. Sorta like the initial idea. Would definitely help me break up my giant `graph` domain, which manages nodes, edges, loading state, ui, and some other stuff.

My gut says that children should finish their work first, then parents.

**Comment by nhunzaker** [comment]
Closing this out again. Sub-domains work well when the state tree is highly nested, but I think domains probably need to stay flat. Nesting largely is necessary for convenience of access, which we can fix by adding a querying API.
