### ISSUE TITLE
Investigate cases where setState doesn't update presenters

### ISSUE THREAD

**Issue by nhunzaker** [vigetlabs/microcosm#188]
Unconfirmed yet, but tracking. Does `setState` not result in a Presenter update?

**Comment by djmccormick** [comment]
Just wanted to follow up with an example of this behavior:

	import React from 'react';
	import ReactDOM from 'react-dom';

	import Microcosm from 'microcosm';
	import Presenter from 'microcosm/addons/presenter';

	class TestPresenter extends Presenter {
		state = { counter: 0 };

		setup() {
			setInterval(() => {
				const newValue = this.state.counter + 1;
				console.log(`Updating the counter to ${newValue}`);

				this.setState({ counter: newValue })
			}, 200);
		}

		view() {
			return <p>{this.state.counter}</p>
		}
	}

	let el = document.body.appendChild(document.createElement('div'));
	ReactDOM.render(<TestPresenter/>, el);

![screen shot 2016-12-01 at 4 26 26 pm](https://cloud.githubusercontent.com/assets/40710/20813337/32ba72e0-b7e3-11e6-8611-92484b0cc7b2.png)

**Comment by nhunzaker** [comment]
Awesome, thank you!

**Comment by nhunzaker** [comment]
Test case:
[presenter-state be3daea]

Checking this out now.

**Comment by nhunzaker** [comment]
Oof. For posterity:

The root of this is a `shouldComponentUpdate` method that I implemented within a special context "sock" inside of the presenter. This wrapper exists to ensure that React context is properly transferred over when extending Presenters. IE10 or lower doesn't transfer static members for ES6 classes.

As for the bug. The reason I did this was to prevent the view model from recalculating too many times when an app changes. If a parent is going to render anyway, there's no sense in recalculating the model when the presenter's subscription fires. Just do it all in the same render.

But, again, _oof_. Sorry. PR shortly.

**Comment by nhunzaker** [comment]
@djmccormick I've sent this out as `microcosm@10.9.0-rc`. I'll publish a full release later today.

**Comment by nhunzaker** [comment]
Upgraded 4 of our projects. Everything's running smoothly. Shipped!

**Comment by nhunzaker** [comment]
microcosm@10.9.0
