### ISSUE TITLE
What if setState in a presenter called the view model again?

### ISSUE THREAD

**Issue by nhunzaker** [vigetlabs/microcosm#189]
I can think of a few use cases:

1. Sifting an existing data set
2. Keeping UI state out of domains

```javascript
class Filter extends Presenter {
    view = UserList

    register () {
        return {
            "filter": (_, state) => this.setState(state)
        }
    }

    model (props, state) {
        return {
            items: ({ users }) => users.filter(u => u.age === state.age)
        }
    }
}
```

We could keep this non-breaking if we checked the arity of `model` to avoid recalculating based on state.

**Comment by greypants** [comment]
downsides? Sounds good to me.

**Comment by nhunzaker** [comment]
None that I can think of. I've got about 20 minutes, I'll get to work.

**Comment by nhunzaker** [comment]
This is on master now. There are a few related outstanding tasks I have for this before I release it. I also need to determine if we need to ship an 11.0.
