### ISSUE TITLE
Pushing action with no params, calls handlers with null

### ISSUE THREAD

**Issue by greypants** [vigetlabs/microcosm#198]
Pushing action with no params, calls handlers with `null` as the second param (after `state`), instead of `undefined`. I noticed the same behavior using `send` from a `withIntent` component.

Code demonstrating the issue:

```js
const Microcosm = require("microcosm").default
const repo = new Microcosm()

const domain = {
  getIntialState() {
    return {
      someToggle: false
    }
  },
    
  register() {
    return {
      'toggleSomeToggle': (state, someToggle) => {
        console.log('someToggle === ' + someToggle)
        return {...state, someToggle}
      }
    }
  }
}

repo.addDomain('domain', domain)

repo.push('toggleSomeToggle')
```

Yields:

```js
"someToggle === null"
```

Demo here: https://runkit.com/greypants/microcosm-issue-198

Explicitly sending along `undefined` yields the same result

```js 
repo.push('toggleSomeToggle', undefined) // toggleSomeToggle === null
```

This prevents setting defaults param defaults like so:

```js
  'toggleSomeToggle': (state, someToggle = true) => { ... }
```

Because `someToggle` is always defined as `null` if no params are passed.

**Comment by nhunzaker** [comment]
Ah interesting. This is because the action payload is `null` by default, and setting a payload to `undefined` is ignored.

Hmm...

**Comment by nhunzaker** [comment]
@greypants give `microcosm@11.1.0-rc0` a shot
