### ISSUE TITLE
Presenter view React Hot Loader Issue

### ISSUE THREAD

**Issue by greypants** [vigetlabs/microcosm#207]
Was trying to add react-hot-loader 3 to the list example app. The index looks like:

```js
class ListIndex extends Presenter {
  view = Index
}
```

Hot loading silently failed. Changing the markup to the following allows components to properly hot-update:
```js
class ListIndex extends Presenter {
  view(props) {
    return <Index {...props } />
  }
```
Ideas why?

**Comment by nhunzaker** [comment]
Hmm. I wonder why. It depends on how the hot loader works...

Possible ideas:

1. React hot loader is checking for JSX, or extension from React.Component
2. React hot loader wraps components in a way that is tripping up the Presenter's view creation logic.

Later is actionable. I'll take a look.

**Comment by greypants** [comment]
Hm. I'll importing react at the top of the first example and see if that makes a difference.

**Comment by nhunzaker** [comment]
Okay. I've got hot loading working...

![hot](https://cloud.githubusercontent.com/assets/590904/22246988/903574aa-e205-11e6-80a1-29da0b5de7e9.gif)

Dang that's cool... Presenter models even hot load. I'll send out a PR once I can figure out how to get test coverage on the change I made to the Presenter.

**Comment by nhunzaker** [comment]
Hot module replacement is working for us on my current project. Could you give it a whirl?

**Comment by nhunzaker** [comment]
Looks like the recommended steps for react hot loader are to use the `<AppContainer>` module to force update the tree, like:

```
<AppContainer>
  <Layout repo={repo} />
</AppContainer>
```

Seems like this basically just listens to hot module events and does a deep `forceUpdate`, which gets around the Presenters using `PureComponent.`
