### ISSUE TITLE
Best way to clear Presenter-forked repo state when a user logs out?

### ISSUE THREAD

**Issue by djmccormick** [vigetlabs/microcosm#210]
Whenever a user logs out of our application, we send the user to our `/login` page. Presenters, through `componentWillUnmount`, seem to instruct their forked repos to tear down (effectively clearing them?). We see the teardown happening, and going to `/login` will have unmounted all the presenters, but we see the old data in the forked repos within presenters after logging back in. In an attempt to address this, we've considered doing `repo.clear` from every domain or presenter when our `logOut` action is called. It's starting to feel like we aren't doing it right. We'll appreciate any guidance you can offer.

**Comment by nhunzaker** [comment]
You should get a fresh fork of the parent repo if your presenter unmounts, and a new one takes its place. 

In the past, we've called `repo.reset()` when a user logs out. That forces all domains to return to their initial state.

Is the same Presenter instance persisting between moving to `/login`, then wherever they land once they have signed in?

**Comment by nhunzaker** [comment]
@djmccormick Didn't want to drop the ball here. I've also been thinking...

What if there were a hard reset that reset an entire tree of forks? You could call it to completely blow away state, restarting from the result of `getInitialState`.

**Comment by nhunzaker** [comment]
In Microcosm 12.x, calling `reset` should operate on the entire network of Microcosm forks. Do you think that helps for your use case here?

**Comment by nhunzaker** [comment]
@djmccormick I think I hit the only other edge case that might produce this in the latest recent 12.1.0-rc release. Basically, if an action was left open, history would always rollback to that point whenever a new action was pushed. This might reproduce state unexpectedly.

This should no longer be the case. However I still want to explore a hard reset, that completely resets from the beginning, wiping away history along the way. What do you think?

**Comment by djmccormick** [comment]
We ended up just ensuring things get unmounted instead of trying to reset. I'm not clear on how reset would work against a repo passed to an effect, say. Is that a fork I'd be clearing? What determines that? At any rate, we are beyond the issue. Thanks for your thoughts on this!
