### ISSUE TITLE
12.0.0

### ISSUE THREAD

**Issue by nhunzaker** [vigetlabs/microcosm#218]
## Last touches:

- [x] Changelog
- [x] Docs pass
- [x] Beta

## Doing:

- [x] `merge(null, {})` should return an object
- [x] Remove commit
- [x] Remove second argument of Domain `commit`
- [x] Replace all instances of "intent" with "action". They are the exact same thing under the hood, and it is a common source of confusion.
- [x] Only serialize for domains that implement serialize
- [x] Rename `Presenter::model` to `Presenter::getModel`. Support using `render` in Presenters.
- [x] Add `this.model` to Presenter to represent last calculated model
- [x] Remove `action.send()`. Was deprecated in 11.6.0
- [x] `reset` should only operate on keys managed by the specific Microcosm. `reset` effects the entire tree.
- [x] `patch` should only operate on keys managed by the specific Microcosm. `patch` effects the entire tree.
- [x] Nested action statuses in registration methods:

## Not doing:

- ~[ ] Update architecture docs based on updates in React Router 4 (having a dedicated presenters folder makes less sense now)~

## Presenter changes

```javascript
class MyPresenter extends Presenter {

  getModel () {
    return { count: state => state.count }
  }

  render () {
    return (
      <ActionButton action={step} value={1}>
        {this.model.count}
      </ActionButton>
    )
  }
}
```

## Action registration changes

```javascript
class Domain {
  //...
  register () {
    return {
      [action]: {
        open  : this.setLoading,
        error : this.setError,
        done  : this.setDone
      }
    }
  }

}
```

**Comment by greypants** [comment]
> Update architecture docs based on updates in React Router 4 (having a dedicated presenters folder makes less sense now)

Interested in where things are headed here.

**Comment by nhunzaker** [comment]
@greypants Aye. Me too. With the component-based API for the new ReactRouter, there ends up being a lot of long relative paths to pull presenters out. Before 4.0, the `routes` file you setup sort of acted like a wireframe for your app. This isn't true anymore.

Also we're discovering similar awkwardness on apps that don't use ReactRouter.

The conceptual separation is still there, without the folder structure. Though I still haven't figured out how to make it clearer that a component is a Presenter just looking at the folder structure. A naming convention might be nice to figure out.

**Comment by mackermedia** [comment]
Adding the ability to do:
```
serialize () {
  return null
}
```
(or some other mechanism) to exclude this particular domain/repo from being included in something like `repo.toJson()` might be nice.

**Comment by nhunzaker** [comment]
@mackermedia added a thing for you:

>  merge(null, {}) should return an object

**Comment by nhunzaker** [comment]
I think we're getting close. I want to figure out if we can fit in #224 while we're making the breaking change to `Presenter::model`
