### ISSUE TITLE
Documentation Typo - Actions

### ISSUE THREAD

**Issue by mackermedia** [vigetlabs/microcosm#228]
![](https://s3.amazonaws.com/vigesharing-is-vigecaring/mackerman/Microcosm_2017-02-23_13-41-51.png.png)

I'd fix, but I'm not sure what it should say! ;)

Seen on http://code.viget.com/microcosm/api/actions.html

**Comment by nhunzaker** [comment]
What! What was I thinking... Alright. I'll figure out some words (or feel free to guess in the mean time).

**Comment by nhunzaker** [comment]
I think this should read:

```
> If we were to write a more low level version of the Promise example earlier:

**Comment by nhunzaker** [comment]
Got it:
http://code.viget.com/microcosm/api/actions.html#return-a-function
