### ISSUE TITLE
action.parallel

### ISSUE THREAD

**Issue by nhunzaker** [vigetlabs/microcosm#229]
What would it look like to batch actions together in parallel?

```
action.parallel(
  initial => first(initial),
  next  => second(next)
).onDone(doSomethingElse)

// or
action.parallel(first, second).onDone(doSomething)
```

Should we just lean on Promise.all, or a similar idea?

**Comment by nhunzaker** [comment]
Subsquently, we could follow up with a `repo.waterfall` and `repo.parallel`. Need to figure out how that fits in to everything else naming wise.

**Comment by keturn** [comment]
Another place where it seems like this fits in neatly to a Promise interface. Your `.parallel` much like [`.all`](http://bluebirdjs.com/docs/api/promise.all.html) or [`.props`](http://bluebirdjs.com/docs/api/promise.props.html) (though Angular's `$q.all` takes either the Array or key-value Object signature).

`.waterfall` is not something I've seen show up in a Promise interface so much, although `q` does [talk about that pattern](http://documentup.com/kriskowal/q/#sequences) and boils it down to `[first, second].reduce(Q.when)`

**Comment by nhunzaker** [comment]
Updating this issue now that we have action sequences using generators in `12.6.0-beta`:

```javascript
export function createMessageAndGoToEditor () {
  return function * (send) {
    let response = yield send(create)

    let message = get(response, 'data.message')

    yield send(setMessageProperties, message)

    yield send(save)

    yield send(navigate, `/messages/${message.id}`)

    yield send(setStep, 'editing')
  }
}
```

I'm pretty happy with this. These sequences can be composed together very easily, and you get an action back that represents the entire workflow. Long term, I could see us shipping a set of addons for simple control flow. Something like:

```
function confirmAndDelete (user) {
  return function * (send) {
    yield send(confirm, `Are you sure you want to delete ${user.name}?`)
    yield send(deleteUser, user.id)
  }
}
```

@keturn I like your idea of just making, what this issue calls `waterfall`, work like `Promise.all`. One thought I had for the future was to always pass the `repo` as the first argument of an action creator. If you returned an action from that, we'd just use that action instead of creating one under the hood:

```javascript
function fetchUser (repo, id) {
  return fetch(`/users/${id}`).then(res => res.json())
}

function fetchUsers (repo, listOfUsers) {
  let requests = listOfUsers.map(id => repo.push(fetchUser, id))

  return Promise.all(requests)
}
```

I'm mostly just worried about confusion there. It's also a breaking change, something I kind of don't want to do for a while. Beyond that -- Would users accidentally call actions directly, like `fetchUsers(this.repo, [1,2,3]`)? In that case, you wouldn't get a `fetchUsers` action dispatched to represent the entire batch operation.

**Comment by nhunzaker** [comment]
We did it!

**Comment by nhunzaker** [comment]
Just to be clear too. This can also be used inside of generators, like:

```
function getUser (id) {
  return ajax.get(`/users/${id|`)
}

function getUsers (ids) {
  return function * (repo) {
    yield ids.map(repo.prepare(getUser)
  }
}
```
