### ISSUE TITLE
Remove Examples from Microcosm Repo

### ISSUE THREAD

**Issue by leobauza** [vigetlabs/microcosm#240]
We should remove the examples folder and move it to their own repo. This way we could lock down the microcosm version an example uses (the chatbot example was broken during a recent change). We could name the repo `microcosm-examples` and have subfolders for what is being showcased on each example (eg. optimistic-updates, progress-states, react-addons, etc)

**Comment by nhunzaker** [comment]
Moved to the `microcosm-examples` package.
