### ISSUE TITLE
Update site/docs

### ISSUE THREAD

**Issue by leobauza** [vigetlabs/microcosm#247]
Main things that need to happen:

- [x] Update the `README.md` with better instructions to run locally and publish
- [x] Add a "Contributing" section
- [ ] ~~Add a "Roadmap" section~~ (see #258)
- [x] Add an overview for each subsection (ie. Introduction, Api, Addons, etc)
- [ ] Review all language for clarity and accuracy

@nhunzaker would like to get your thoughts on what I am proposing to add (ie. contributing section, roadmap, overviews).

**Comment by nhunzaker** [comment]
I kind of did:

> Add an overview for each subsection (ie. Introduction, Api, Addons, etc)

What do you think?

**Comment by leobauza** [comment]
Yeah, the only thing missing is an explanation of the difference between API and Addon. That is that the Addons are specific to react and API doesn't depend on a framework. But yeah your overviews pretty much covered what we needed. The quickstart or architecture section can make the division clearer when introducing concepts.

**Comment by leobauza** [comment]
Closing and moving to the road to JSDoc #316
