### ISSUE TITLE
Action nomenclature

### ISSUE THREAD

**Issue by nhunzaker** [vigetlabs/microcosm#268]
The term `action` is currently overloaded. I have a bad habit of changing names on this project, something I don't want to do too much more of in the future, but the term `action` is really overloaded and I get a lot of questions clarifying what is an action vs whatever you get from `repo.push(thing)`. 

I don't want a breaking change, but want to make the distinction clearer between these two pieces:

```javascript
// 1 - What do we call this?
function addUser (params) {
  return fetch.post('/users', params).then(response => response.json())
}

// 2 - What do we call this?
let whatToCallThis = repo.push(addUser, { name: 'Billy' })
```

Here's what I'm thinking:

1. The thing you pass to `send()` and `repo.push()` is an action. There's no change here.
2. The thing you get back from `repo.push()` is a _Task_

I think this sounds very natural, but we might want to add some aliases for a few of the methods that update a task. The sequence could be:

- `task.start()` - aliases `task.open()`
- `task.update()` - no change
- `task.done()` - aliases `task.resolve`
- `task.error()` - aliases `task.reject`
- `task.cancel` - no change

We already have these aliases for actions, so you can subscribe to `action.done` and `action.resolve`. This also increases consistency with `task.onDone` and `task.onError`, which might be a good change to make regardless.

Overall, this could look like:

```javascript
function wait (time) {
  return task => {
    task.start()

    let timeout = setTimeout(task.done, time)

    task.onCancel(() => clearTimeout(timeout))
  }
}

let task = repo.push(wait, 1000)

// Just kidding!
task.cancel()
```

**Comment by mackermedia** [comment]
👍

**Comment by h0tl33t** [comment]
I like `task` for this a lot!  🥇

**Comment by keturn** [comment]
If "the thing you get back from repo.push" is the single asynchronous result of some one-time action, and any callbacks you register on it will be called no more than once (unlike the callbacks you register from Domains), that sounds a lot like a Promise (or Deferred).

Not all implementations of Promise have _abort_ and _update_ methods (the version of Promise that made it in to ES6 has neither, and Bluebird seems to have decided that `cancel` should mean "ignore results" rather than "abort operation in progress"), but there's certainly precedent for both.

**Comment by nhunzaker** [comment]
> Bluebird seems to have decided that cancel should mean "ignore results" rather than "abort operation in progress")

@keturn This is extremely helpful to know, thank you! This is how `repo.history.wait()` works for waiting for all current actions to complete. Cancelled actions are ignored. I was really stressing out about if I made the right call there.

It also helps for deciding how to handle cancellation in `action.waterfall` and `action.parallel` (which don't have fixed names yet)

**Comment by keturn** [comment]
I don't follow Bluebird's development, but it looks like that was a change they made between their version 2.x and 3.0. In a [related issue](https://github.com/petkaantonov/bluebird/issues/308#issuecomment-55331070), kriskowal linked to a [detailed piece on promise cancellation](https://github.com/kriskowal/gtor/blob/master/cancelation.md).

**Comment by nhunzaker** [comment]
Wow. This is definitely something for me to chew on. Thank you so much for sharing this. 

I am very interested in the idea of adopting some sort of async data structure pattern for Actions. I had been looking at Observables (via something like https://github.com/zenparsing/zen-observable), but I'm still evaluating if there's an API mismatch.

Microcosm actions work separately from promises, we just expose a `.then()` method for interoperability. This improves integration with other libraries. For example, using `async/await` with [Jest](https://github.com/facebook/jest) to wait for an action to complete, binding the failure of the action to a test failure. 

So this [whole gtor readme](https://github.com/kriskowal/gtor/blob/master/README.md) is exactly what I wanted, thank you!

**Comment by keturn** [comment]
> Microcosm actions work separately from promises, we just expose a .then() method for interoperability.

I know you think that :grinning: but the thing I'm trying to tease out is _why._ If it walks like a Promise and it quacks like a Promise, what do you get out of not calling it a Promise?

**Comment by nhunzaker** [comment]
Long term, I'd like Actions to follow observables. Presenters and action creators already understand them. I'll follow up in a future doc with some design thoughts.

Thanks everyone for the discussion!
