### ISSUE TITLE
Case Study: Please Sign In To Continue

### ISSUE THREAD

**Issue by keturn** [vigetlabs/microcosm#274]
**What kind of issue is this?** (check at least one)

- [X] Discussion

(If there's a better venue for discussion, let me know, but this issue tracker is the only communication forum for Microcosm I could find.)

**What version of Mircrocosm is this for**

11

**Steps to Reproduce/Example** (if applicable)

We've been trying out Microcosm on a pretty small app, it just has a few more moving parts than the "list of planets" tutorial, and I'm having trouble arranging things in a way that feels like it fits a Microcosm architecture.

Our app acts on one or more Conversation views.

When the user clicks an "Insert Links Here" button, we want to display a dialog that allows them to pick appropriate options.

We must have a session with our server in order to open that dialog.

It's easy to have an Action for "focus for insertion", so when the user clicks a button the Domain updates the Repo to say "Conversation 7 requests links." This action is synchronous.

And we have an asynchronous IsSessionCurrent function we can call. We could return that as a Promise from an Action-constructor. A Domain could use that to set an `isSessionCurrent` value in the repo.

...past that point, things get murky.

Is it the job of the button's onClick handler to fire both of those actions? That would require all the buttons to know which things need an active session and which don't, which sounds like a bad dependency.

As an alternative, should `repo.push(checkSession)` be called from an Effect that responds to `focusForInsertion`? Actions that lead to Effects that lead to more Actions — I can't tell if that way lies madness or if that's run-of-the-mill here. (or both.)

Then how do I make a presentation layer show the dialog if and only if something is focusedForInsertion **and** we have a valid session?

We started out not using any of the prepackaged Presenter offerings, since most of our actual DOM interactions are through another SDK, but even after reading over much of the code for the Preact presenter I'm still not sure how it would help me here.

I think that if I got all that cleared up, it would put me on the right track, but there is one more significant piece of this flow worth mentioning:

If we _don't_ currently have a valid session, we're going to have to kick off a sign-in process for one. (From an Effect on checkSession.error? or checkSession.done, but only if it's returned False?) From the Repository's perspective, that sign-in process is going to be mostly out-of-band, but at some point the app may get an event saying "Hey, you have a session now!"

At which point it should go ahead and show the link-request dialog if there's still something focused that's requested one.

It's occurred to me that an alternative to these synchronous or asynchronous-but-fast-and-simple would be to try to make a longer-lived Action that is not `done` until the entire sign-in process is complete, but it's not clear how I would get that outside "you have a session now" event to resolve an existing in-progress Action.

The idea of being able to do optimistic updates and the sort of state management that can resolve things if they didn't play out as "optimistically" as assumed has been very attractive. (with a nice debuggable view of state changes! and maybe a sort of built-in undo stack!) But a considerable number of hours into this now and still unsure about how to work a sign-in dialog has me questioning if this is in fact an appropriate tool for the job.

Thanks for any light you can shed on this subject!

**Comment by keturn** [comment]
Prompted by #268, I went and re-read the Action docs. When I initially read them for version 11, I don't recall coming away with the impression that `repo.push(action)` returned any value at all; I was working under the belief that the only code that responds to the completion of an action is registered on a Domain and/or Effect.

Knowing that I can do `repo.push(action).then(otherStuff)` opens up other possibilities, though I haven't yet had any 💡 "aha!" moments about how that solves everything for me.

**Comment by nhunzaker** [comment]
@keturn Sequential actions is an area of research for us. It would be great to be able to abstract this away from the presentation layer as much as possible.

Was `.then()` enough to get you unstuck? Anything else we can provide clarity on?

**Comment by nhunzaker** [comment]
Closing this out. Happy to keep discussing though :)
