### ISSUE TITLE
Add warning when trying to patch a key that doesn't exist

### ISSUE THREAD

**Issue by greypants** [vigetlabs/microcosm#277]
We should add a `console.assert` that warns the user when trying to patch a domainless key.

#### Excerpts from slack
@nhunzaker: 
> when you patch/reset, it will only operate on keys managed by a microcosm
> so if you do a patch/reset on a fork, it won't blow away all state
> that way if you patch in a fork, you don't accidentally set state on the parent
> which would cause state to always reset to the parent, which doesn't manage that part of state

The following test would fail because no `planets` domain has been added:

```  it('is a test!', () => {
    const repo = new Microcosm()
    repo.patch({
      planets: [{ name: 'Tatooine' }, { name: 'Dagobah' }]
    })
    expect(repo.state.planets).toBeDefined()
  })
```

This is intentional— we just need to add a warning explaining that.

**Comment by greypants** [comment]
@leobauza probably need to explain this in the docs as well.

**Comment by nhunzaker** [comment]
This will be covered in 13.x
