### ISSUE TITLE
Lifecycle methods?

### ISSUE THREAD

**Issue by jbelcher** [vigetlabs/microcosm#28]
Just wanted to open an issue to think through a some potential hooks. When an action resolves? Before/after a dispatch? When a microcosm resets or replaces?

**Comment by nhunzaker** [comment]
Just to get some use cases in here:

1. Undo/Redo - travel along revisions to start. Useful for users to return to a previous state
2. Rewind/FastForward - travel along resolved actions. Useful for developers to debug complete life cycles

**Comment by jbelcher** [comment]
Might also be a good way to do more with error states/rollbacks

**Comment by nhunzaker** [comment]
Actually, I _almost_ put that. You could monitor actions, persist them in the background, and handle reconciling the returned record or rolling back if need be.

**Comment by jbelcher** [comment]
Yeah FWIW that's super attractive to me—a lot of flux libraries get too opinionated w/ magic/abstractions. around things like that. I really like how clean/clear microcosm is in its current state.

**Comment by nhunzaker** [comment]
Played around a bit with it today. Right now we call transactions "signals", but it's an internal API; I can change it without much fuss.

So far I have:

```javascript
didStart     : function(app) {},
willDispatch : function(app, transaction, action, result) {},
didDispatch  : function(app, transaction, action, result) {}
```

I have this in the https://github.com/vigetlabs/microcosm/compare/master...lifecycles branch with some interesting results:

![redo](https://cloud.githubusercontent.com/assets/590904/7799316/af55c8d0-02d2-11e5-9cc5-6114a45f82b4.gif)

**Comment by jbelcher** [comment]
Really nice—feels flexible too. You can persist app states or signals and annotate either pretty easily w/ what's there.

**Comment by nhunzaker** [comment]
Cool. There's no going back from this (a major release, I guess :smile_cat:) , so I definitely want to get this right. 

I'd like to continue to mature a reference implementation. I have a few unanswered questions:

1. How does undo/redo expose itself in an application?
2. I sort of stumbled upon this idea of treating actions transactionally, but I really like it. Should we ensure some sort of resolution order?
3. What about rewriting transaction history? [Datomic has the idea of retraction](http://docs.datomic.com/transactions.html#sec-3-6), but maybe that is too high level for Microcosm. Still, what if each transaction had an enabled state or something that allowed you to "forget" that something happened? 

I do not think that we need answers for questions 2 and 3 yet, but I am very curious about question 1.

**Comment by nhunzaker** [comment]
Beyond that, do the names and parameters of these life cycle methods feel good?

**Comment by jbelcher** [comment]
Yeah the names/params feel good. 

> 1. How does undo/redo expose itself in an application?

Yeah that's a bit tricky w/ the current model, since you're not exactly applying an inverse action—you're going back to a previous app state (and that implies something acting globally). I wonder if it'd make sense to allow plugins to attach methods like a mixin on app? Or maybe access plugin methods via an interface on app? Maybe plugin "actions" make more sense? That could get hairy though. 

> 2. Should we ensure some sort of resolution order?

I feels like a good guarantee. Does an action transaction imply that it will roll back the entire action if a store throws? While that might protect against inconsistent states it does feel like it breaks store encapsulation a bit. 

> 3. Still, what if each transaction had an enabled state or something that allowed you to "forget" that something happened. 

Yeah that seems like a good way to handle that, although it does require a playback to reconcile the correct new state. I'm not sure what the alternative would be (some sort of diffing between the app states which you could merge, sort of like a revert commit?). Either way keeping history rather than removing it seems correct.

**Comment by nhunzaker** [comment]
@jbelcher The application itself is a data store, it just farms out data reduction to other stores. What if an application could respond to actions itself? I am unclear how this would work with plugins, but the microcosm could respond to actions fired by them.

**Comment by jbelcher** [comment]
@nhunzaker that seems reasonable to me.

**Comment by nhunzaker** [comment]
Now that we have guarantees about execution order of transactions, I think it's time to revisit this thread. Right now, I think there are a few key moments in the lifecycle (in order):

1. start
2. state resets
3. A transaction is created
4. An invalid transaction is purged
5. Complete transactions are "squashed down" and released
6. Transactions "roll forward", determining new state
7. state changes

I think I probably need to create an example that visualizes the transaction process better. That might identify the key points we need to expose for full transparency.

**Comment by nhunzaker** [comment]
Finally got this with #94. Basically we turned Microcosm inside out, exposing lifecycle methods to implement most internal logic.

**Comment by nhunzaker** [comment]
Going to finally close this one out. lifecycle methods for plugins will stay private for a bit until we can vet the names, but I think we're finally there!
