### ISSUE TITLE
Pass along data to action.open callback when returning a promise

### ISSUE THREAD

**Issue by greypants** [vigetlabs/microcosm#296]
When actions return a promise, It would be convenient if callbacks registered with `action.open` received the original payload. The main use case being for performing optimistic updates before hearing back from the server.

```js
function updateFoo(data) {
  return ajax.patch('foo', data)
}

repo.push(updateFoo, { foo: 'bar'})

// ...elsewhere in a domain or effect:
register() {
  return {
    [updateFoo.open]: data => console.log(data) // undefined instead of { foo: 'bar'}
  }
}
```

Here's where the work needs to be done: https://github.com/vigetlabs/microcosm/blob/master/src/coroutine.js#L51-L60

**Comment by nhunzaker** [comment]
This is in the current alpha, if you'd like to give it a spin:

`yarn add microcosm@12.7.0-alpha.4`

**Comment by greypants** [comment]
It's working great! A+
