### ISSUE TITLE
Investigate API documentation generation with Documentation

### ISSUE THREAD

**Issue by nhunzaker** [vigetlabs/microcosm#307]
[Documentation.js](https://github.com/documentationjs/documentation) supports Flow out of the box. It would be super cool if we could use it to autogenerate API docs.

I'd like to see a couple of things happen:

- [ ] Generate a markdown file for a Flow Typed class in `docs/api/<class>.md`
- [ ] Use that markdown file to generate a page in our website docs

**Comment by efatsi** [comment]
@nhunzaker cool to close this if we're focusing efforts on JSDoc?

**Comment by nhunzaker** [comment]
Sure can.
