### ISSUE TITLE
create-microcosm-app

### ISSUE THREAD

**Issue by nhunzaker** [vigetlabs/microcosm#332]
Yarn has recently added a new feature: `yarn create`. It can be used to do some pretty neat stuff:
https://yarnpkg.com/blog/2017/05/12/introducing-yarn/

Let's make a `create-microcosm-app` or just `create-microcosm` to help people get started right away. Instead of cloning in the quick start, what if we said:

> After yarn finishes installing, create a microcosm:
> 
> `yarn create microcosm`

**Comment by efatsi** [comment]
absolutely 👍

**Comment by efatsi** [comment]
Threw this together today leaning on some work from `create-react-app`: https://github.com/vigetlabs/create-microcosm

A lot of work to still be done, but it works with `yarn create microcosm project-name`. We can move conversation to that repo for next steps (of which there are a lot...)
