### ISSUE TITLE
Quick Start - limit React Router version

### ISSUE THREAD

**Issue by mzlock** [vigetlabs/microcosm#344]
**What kind of issue is this?** (check at least one)

- [ ] Report a bug
- [ ] Feature Request
- [ ] Question
- [ ] Discussion
- [ ] Documentation
- [X] Other, please describe:

The React Router version for the microcosm quick-start needs to be versioned. The newest version of React Router that installs automatically gives an error.

Same issue as here:
https://github.com/acdlite/redux-router/issues/281

React router version `3.0.5` works fine.

**What version of Microcosm is this for**
`12.8.0`

**Steps to Reproduce/Example** (if applicable)
Follow the quick-start steps:
http://code.viget.com/microcosm/guides/quickstart.html

**Comment by nhunzaker** [comment]
Looks like React Router was upgraded to 4, but without changing the usage format. React Router 4 changes some stuff around that we need to discuss as a group. In the mean time, I'll downgrade the quick start to React Router 3.

**Comment by nhunzaker** [comment]
Done. I'll follow up with an issue to discuss how we want to adjust our structure for React Router 4, where there isn't a central routing file.
