### ISSUE TITLE
Link to actions.md no longer works

### ISSUE THREAD

**Issue by averyvery** [vigetlabs/microcosm#35]
Here:

https://github.com/vigetlabs/microcosm/blob/master/docs/guides/hello-microcosm.md#more-on-how-actions-work

Should be updated to point to

 https://github.com/vigetlabs/microcosm/blob/master/docs/api/actions.md

**Comment by averyvery** [comment]
There's a similar issue here:

https://github.com/vigetlabs/microcosm/blob/master/docs/api/actions.md

"The two ways to write actions" at the top links to a missing .md.

**Comment by nhunzaker** [comment]
Looks like my method of relative linking was off for the first issue. Both have been fixed.
