### ISSUE TITLE
Ability to set history length externally

### ISSUE THREAD

**Issue by nhunzaker** [vigetlabs/microcosm#353]
For the dev tools, I want to allow a user to not have to worry about adding `maxHistory: Infinity` when in development mode. It would be great if there was a way to adjust the settings of the history object externally, like:

```
repo.history.setLimit(Infinity)
```

**Comment by efatsi** [comment]
@prayasht think you might able to tackle this one?

**Comment by nhunzaker** [comment]
We just need to update this field:

https://github.com/vigetlabs/microcosm/blob/master/src/history.js#L26

This assignment could probably be moved into a method.

**Comment by prayasht** [comment]
I can tackle this one. 

Would it look something like this?

```javascript
class History extends Emitter {
  // ...

  setLimit(limit: number) {
    this.limit = limit
  }

  // ...
}
```
