### ISSUE TITLE
Domain state change -> Presenter.model state not updating

### ISSUE THREAD

**Issue by mackermedia** [vigetlabs/microcosm#366]
**What kind of issue is this?** (check at least one)

- [X] Report a bug
- [ ] Feature Request
- [ ] Question
- [ ] Discussion
- [ ] Documentation
- [ ] Other, please describe:

**What version of Microcosm is this for**

12.9.0

**Steps to Reproduce/Example** (if applicable)

I attempted to add what I think is a [valid failing test](https://github.com/vigetlabs/microcosm/commit/8d63dfa393919fdebf102ec156eaa13a313d8bc5). Without adding the domain and triggering an action (using `repo.patch` to update state) it seemed to work fine, however when using an action to trigger domain state change it seems the presenter model state is not changing.

I can provide more detailed logs and investigation from the project I'm using it that has the broken functionality if needed.

**Additional Comments** (optional)

I <3 Microcosm. Keep up the great work!

**Comment by nhunzaker** [comment]
Cool. Thanks for the reproduction! I'll check it out.

**Comment by nhunzaker** [comment]
Resolved in 12.9.0-beta4 by #369.

What a 😵 🔀 🐛
