### ISSUE TITLE
Returning an Action Param that is a Function (but not a thunk)

### ISSUE THREAD

**Issue by solomonhawk** [vigetlabs/microcosm#367]
I'm not 100% sure whether this would be considered a bug or feature request - so I tagged it as both and as a question. Changing this _may_ be considered a breaking change but I wanted to get some input on that, too.

**What kind of issue is this?** (check at least one)

- [x] Report a bug
- [x] Feature Request
- [x] Question
- [ ] Discussion
- [ ] Documentation
- [ ] Other, please describe:

**What version of Microcosm is this for**

All, (using 12.9.0-beta3 now)

**Steps to Reproduce/Example** (if applicable)

Say you have an action:

```js
function makeAThing(doSideEffect) {
  return doSideEffect
}
```

And you call this action with a function as the argument:

```js
repo.push(makeAThing, function() {
  launchSatelliteIntoOrbit()
  fireZeMissiles()
  return 'Nothing happened.'
})
```

Microcosm's `coroutine` will treat this as a thunk (function body form) and will call the function `doSideEffect` and then return the action.

**Question**: Should coroutine be able to distinguish between an action that returns a function-param and a true thunk?

**Expected**: If the function-argument has side-effects and the user intends to call it later then it is unexpected for that function to be executed as part of the action resolution step.

**Context**: I'm working on expanding the `react-router` examples with some other use cases. One of those is blocking `history` from a route change and prompting the user for confirmation. `history.block` has two forms, one of which is a callback function that returns `Maybe<String>` - if it returns a string then `history` prompts the user with that string otherwise the route change proceeds. One thing I'm exploring is passing that function straight through as the action argument hence this issue.

**Comment by nhunzaker** [comment]
In 12.12.0
