### ISSUE TITLE
A Presenter's "update" method is not run when the model changes

### ISSUE THREAD

**Issue by djmccormick** [vigetlabs/microcosm#372]
**What kind of issue is this?** (check at least one)

- [x] Report a bug
- [x] Feature Request
- [x] Question
- [ ] Discussion
- [ ] Documentation
- [ ] Other, please describe:

**What version of Microcosm is this for**

I ran the example code in `12.9.0-beta4` and `12.8.0` with the same results.

**Steps to Reproduce/Example** (if applicable)

I expected that a Presenter's `update` method to be run whenever the Presenter's model changes, but this doesn't appear to be the case. [The documentation](https://github.com/vigetlabs/microcosm/blob/master/docs/api/presenter.md#updaterepo-nextprops-nextstate) states:

> update is always executed after the latest model has been calculated.

Here is a a bit of example code illustrating the behavior I'm experiencing:

	import React from 'react';
	import ReactDOM from 'react-dom';

	import Microcosm from 'microcosm';
	import Presenter from 'microcosm/addons/presenter'

	//
	// SETUP THE TEST
	//

	// Action
	function increment() {
		return true;
	}

	// Domain
	class CounterDomain {
		getInitialState() {
			return 0;
		}

		register() {
			return {
				[increment]: this.handleIncrement
			};
		}

		handleIncrement(state) {
			return state + 1;
		}
	}

	// Presenter
	class Test extends Presenter {
		setup(repo) {
			repo.addDomain('counter', CounterDomain);
		}

		getModel() {
			return {
				counter: state => state.counter
			};
		}

		ready(repo, props, state) {
			console.log('ready', this.model.counter);
		}

		update(repo, nextProps, nextState) {
			console.log('update', this.model.counter);
		}

		render() {
			console.log('render', this.model.counter);

			return (
				<div>
					Counter is at: {this.model.counter}
					<hr/>
					<a href="" onClick={this.handleClick.bind(this)}>Increment</a>
				</div>
			);
		}

		handleClick(evt) {
			evt.preventDefault();
			this.repo.push(increment);
		}
	}

	//
	// RENDER THE TEST
	//

	ReactDOM.render(
		<Presenter repo={new Microcosm()}><Test/></Presenter>,
		document.getElementById('root')
	);

Here's a screenshot after clicking the "Increment" link six times (notice we never see an "update" string logged):

![screen shot 2017-07-24 at 2 29 25 am](https://user-images.githubusercontent.com/40710/28510730-f9c9e194-7017-11e7-8247-64e01f22f7e1.png)

Is `update` supposed to be run in this case? If not, what is the recommended method for reacting to model updates in a Presenter?

**Comment by nhunzaker** [comment]
Hey @djmccormick, thanks for the great write up!

`update` does not get called when the model updates. This is to avoid accidental infinite loops (the model changes, you push an action, the model changes, you push an action, and so on).

The documentation _intended_ to say that the latest model is available when update is called. 

Presently, we don't have a lifecycle hook for when the model updates, but we _could_. What do you think of something like:

```javascript
modelWillUpdate (repo, nextModel) {
  // do a check, this.model is the last model
}
```

Totally open to a different name. And we'll fix the documentation to be clearer.

**Comment by efatsi** [comment]
@nhunzaker would there again be a risk of triggering an infinite loop if `modelWillUpdate` pushed an action?

**Comment by nhunzaker** [comment]
@efatsi Yes.

**Comment by efatsi** [comment]
👍  let's make that super clear in the docs if we end up implementing something like this. How do we feel about `modelWillUpdate` and/or `modelDidUpdate`? @djmccormick did you have a specific use case in mind?

**Comment by solomonhawk** [comment]
That line in the docs is misleading - here's an amended version #375 

I like the idea of escape hatches for hooking into model update lifecycles and the symmetry of `modelWillUpdate`/`modelDidUpdate` with `componentWillUpdate`/`componentDidUpdate`. I too am curious about specific use cases. This has not come up as a need yet in any of the projects I've used Microcosm for.

**Comment by djmccormick** [comment]
While I do think the docs could be clearer in this case, I've considered my specific use case (and tried to dream up hypothetical ones) and I've decided I'm just doing it wrong. It's nothing I can't do using the promise that comes back from my action or intent handler call. In fact, if the new lifecycle methods pondered above existed, I'm confident I would've 2:00AM-coded myself into a more brittle solution than what I've now done. I encourage you to leave them out unless someone comes up with a valid use case.

Thanks for your feedback on my issue, and thanks to @solomonhawk for the PR clarifying things in the docs. And thanks, of course, for creating and maintaining the best data and state management tool I've ever used.

**Comment by mackermedia** [comment]
+1 to `modelWillUpdate`/`modelDidUpdate`. 

I recently had an issue trying to hook into model data changes using `.update` and found that a Presenter's `.update` wasn't getting called because Presenter `.teardown` was getting called first. 

I was thinking ☝️ could be a separate issue, but adding the more explicit hooks for data changes seems like it would make this irrelevant.

**Comment by nhunzaker** [comment]
@djmccormick I've added a `modelDidUpdate` method in `microcosm@12.13.0-rc`:
http://code.viget.com/microcosm/api/presenter.html#modelwillupdaterepo-nextmodel-changeset

```
import { getPlanet } from '../actions/planets'
import { find } from 'lodash'

class Planet extends Presenter {
  getModel(props) {
    let { id } = props.location.query

    return {
      id: id,
      planet: state => find(state.planets, { id })
    }
  }
  modelWillUpdate(repo, nextModel, changeset) {
    if ('id' in changeset)
      repo.push(getPlanet, changeset.id)
    }
  }
  // ...
}
```

I am hesitant about the ability to produce infinite loops, but it patches a hole I think we've had in the presenter API for a long time. 

Please let me know what you think!
