### ISSUE TITLE
Publish to CDN

### ISSUE THREAD

**Issue by solomonhawk** [vigetlabs/microcosm#373]
**What kind of issue is this?** (check at least one)

- [ ] Report a bug
- [ ] Feature Request
- [ ] Question
- [ ] Discussion
- [ ] Documentation
- [x] Other, please describe:
Request to publish microcosm on a CDN.

**What version of Microcosm is this for**

All

**Additional Comments** (optional)

Publishing Microcosm to a CDN would help reduce the friction of submitting a bug report with a reproducible test case. If Microcosm was available via a CDN then we could easily lean on something like CodePen or JSFiddle for sharing minimal test cases.

**Comment by nhunzaker** [comment]
Yes. For this to happen:

- We need to publish a UMD bundle
- We should publish UMD bundles for the last 4 minor releases of the last 2-3 major versions
- Let's make a test play ground that we publish to our website, but we can start with CodePen or JSFiddle too.

**Comment by nhunzaker** [comment]
cc @mackermedia cares about this too.

**Comment by nhunzaker** [comment]
Related to #362

**Comment by nhunzaker** [comment]
See "Suggested Workflow" here:
https://unpkg.com/#/

**Comment by nhunzaker** [comment]
This will start being a thing in 12.10.0:
https://unpkg.com/microcosm@12.10.0-alpha.0/umd/microcosm.js
