### ISSUE TITLE
Add hook to ActionButton for modifying action payload

### ISSUE THREAD

**Issue by solomonhawk** [vigetlabs/microcosm#381]
**What kind of issue is this?** (check at least one)

- [ ] Report a bug
- [x] Feature Request
- [ ] Question
- [ ] Discussion
- [ ] Documentation
- [ ] Other, please describe:

**What version of Microcosm is this for**

All

**Steps to Reproduce/Example** (if applicable)

If I want to change the payload of an `ActionButton` based on the `event` object I have to revert to just using `button` and `withSend`.

**Comment by nhunzaker** [comment]
In 12.12.0. Thanks for doing this!
