### ISSUE TITLE
Add `removeEffect` API method

### ISSUE THREAD

**Issue by solomonhawk** [vigetlabs/microcosm#383]
**What kind of issue is this?** (check at least one)

- [ ] Report a bug
- [x] Feature Request
- [ ] Question
- [ ] Discussion
- [ ] Documentation
- [ ] Other, please describe:

**What version of Microcosm is this for**

All

**Additional Comments** (optional)

I have a use case where I want to model a one-time occurrence as an Effect. After it is triggered, I don't need the effect anymore at all. It seems like this would be a probably insignificant performance improvement where Microcosm wouldn't need to call the Effect handlers after it is removed.

**Comment by nhunzaker** [comment]
Since effects are Subject observables, In 13.x, you can do this with:

```
this.complete()
```

or 

```
effect.complete()
```
