### ISSUE TITLE
Add hint how to run examples to README.md

### ISSUE THREAD

**Issue by flof** [vigetlabs/microcosm#39]
It took me while to find out the following steps:

 - `npm install`
 - `npm run-script start`
 - Open http://localhost:8080

These instructions are actually already in the CONTRIBUTING.md file. But I think this is not the best place for new users.

**Comment by nhunzaker** [comment]
Good idea! How does this look?

https://github.com/vigetlabs/microcosm#examples

**Comment by flof** [comment]
Looks great. 
One small thing: the first sentence misses a "be", I guess. 

Examples can **be** found in...

**Comment by nhunzaker** [comment]
@flof Oh dear... Looks like I got ahead of myself!
