### ISSUE TITLE
Rethinking/simplifying Domains

### ISSUE THREAD

**Issue by nhunzaker** [vigetlabs/microcosm#395]
We write a lot of apps with client-only state. This can result in a lot of boilerplate code. Consider:

```javascript
const toggleConfirm = n => n
const toggleFeedback = n => n
const notify = n => n
const showMenu = n => n
const setTitle = n => n

class Session {

  getInitialState() {
    return {
      showConfirm: false,
      showFeedbackDialog: false,
      notification: '',
      showMenu: false,
      title: ''
    }
  }

  toggleConfirm(session) {
    return update(session, 'showConfirm', value => !value)
  }

  toggleFeedback(session) {
    return update(session, 'showFeedbackDialog', value => !value)
  }

  setNotification(session, message) {
    return set(session, 'notification', message)
  }

  showMenu(session, display) {
    return set(session, 'showMenu', display)
  }

  setTitle(session, title) {
    return set(session, 'title', title)
  }

  register() {
    return {
      [toggleConfirm]: this.toggleConfirm,
      [toggleFeedback]: this.toggleFeedback,
      [notify]: this.setNotification,
      [showMenu]: this.showMenu,
      [setTitle]: this.setTitle
    }
  }
}
```

**This is too much boilerplate**. We do these same interactions all the time, particularly for domains that operate on an object:

- Set 
- Reset
- Toggle

So let's figure out how to simplify this. Long term, I think it would be cool to specify domains in terms of a GraphQL schema. This is a long road. In the short term, I think we could get something together that would benefit our projects within a short period of time:

```javascript
import { Struct } from 'microcosm/resource'

const Session = Struct({
  showConfirm: false,
  showFeedbackDialog: false,
  notification: '',
  showNotification: false,
  showMenu: false,
  title: ''
})

export const toggleConfirm = Session.toggle('showConfirm')

export const toggleFeedback = Session.toggle('showFeedbackDialog')

export const notify = Session.set('notification')

export const showMenu = Session.toggle('showMenu')

export const setTitle = Session.set('title')

export default Session
```

**Registering to other actions**

We could still allow this:

```javascript
Session.register(action, (state, payload) => {
  // operate on data
})

Session.register(action, {
  done: (state, payload) => {},
  error: (state, payload) => {}
})
```

**Outstanding questions**

1. This should live as a separate project until it becomes more formal: `microcosm-resource` maybe.
2. I've only covered a `Struct` example, but we could do this for lists too
3. I would like to explore using combinations of `Struct` and `List` domains through nesting.
4. Collocating actions and domains is new: we should sync up on how this might impact our project structure. Still, I like the idea of just going to `session` or `widgets` to see all of the associated actions.

**Comment by nhunzaker** [comment]
cc @mackermedia

**Comment by efatsi** [comment]
👍  to something like `Session`. 👎  to something like `microcosm-resource`, but that's just my gut reaction to splitting up js packages.

**Comment by mackermedia** [comment]
👍 What Eli said. I'd prefer to make this an optional add-on in microcosm vs. having to pull in another package and remember where all the things live.

**Comment by nhunzaker** [comment]
Thinking has evolved a bit here. See #441
