### ISSUE TITLE
Options passed to domain on creation don't include the key of their mount point in the repo

### ISSUE THREAD

**Issue by djmccormick** [vigetlabs/microcosm#396]
**Is this a feature, bug, or something else?**
Feature request

**What is the current behavior?**
The options passed to a domain on creation don't include the key of their mount point in the repo.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/w2m0mang/).**

**What is the expected behavior?**
Having the key would be useful in my case where I'm trying to re-hydrate my domain from state that was provided through a global as the end result of server-side rendering.

**Which versions of Microcosm is affected by this issue?**

**Comment by nhunzaker** [comment]
Good idea! Let me see what I can do....

**Comment by nhunzaker** [comment]
This has landed in Microcosm 12.12.0
