### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by g-clef** [vigetlabs/microcosm#501]
**Is this a feature, bug, or something else?**
Something else.

**What is the current behavior?**
There is no distribution license specified in a LICENSE.md file or in the README

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/w2m0mang/).**
n/a

**What is the expected behavior?**
A license file defined.

**Which versions of Microcosm is affected by this issue?**
n/a

I think it would be helpful if you could include a LICENSE.md file, so that users outside viget (hi, guys) would know how we can include microcosm in projects/products. (For example, if I'm using microcosm, do I need to put a link to here, or to viget, or some other place on my site? Or do you want attribution?)

**Comment by nhunzaker** [comment]
Hey! Sorry, we're MIT all the way. 

We moved things to a multi-package repo, the licenses got put in the individual project folders. For example:
https://github.com/vigetlabs/microcosm/blob/master/packages/microcosm/LICENSE

This license should ship with everything sent to npm, but I'll throw another license file in the repo root and reference it in the README for good measure.

Thanks for calling it to our attention!

**Comment by nhunzaker** [comment]
This is now on master. Thanks for calling it out!
